### ISSUE TITLE
大佬还打算做明日方舟的防沉迷破解吗

### ISSUE THREAD

**Issue by 16alpha** [long45343/Arknights_OCR_Material-design-2-APP#1]
孩子要哭了。因为防沉迷没法参与2.5周年的活动。如果大佬愿意的话可以私发给我，我绝对不会外传，求求了，想上线戳戳老婆们！

**Comment by Eleven11486** [comment]
未成年菜鸡加一，本来就够痛苦了，没想到还是被背刺了，请求大佬下凡

**Comment by morettiL** [comment]
球球大佬救救了，惨遭背刺，哪位大佬研究好了能私一份嘛，感激不尽

**Comment by Ethan114514** [comment]
未成年惨遭背刺，哪位大佬研究好了能私发我一份嘛，不胜感激

**Comment by Siiwjj** [comment]
啊啊啊求求了有木有iOS的
